apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dojo-k8s-hpa
spec:
  maxReplicas: 100
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dojo-k8s
  targetCPUUtilizationPercentage: 50